obj-m += monitor_syscall.o

all:
	make -C /home/zhang/research/imx53/liboot-tz/linux-2.6.35-imx/ M=$(PWD) modules

clean:
	make -C /home/zhang/research/imx53/liboot-tz/linux-2.6.35-imx/ M=$(PWD) clean
